### ISSUE TITLE
FEATURE REQUEST: Transmiterea indexului

### ISSUE THREAD

**Issue by mdalacu** [cnecrea/hidroelectrica#1]
Salut, ar fi frumos sa poata transmite indexul la o data prestabilita daca ai vreo monitorizare inteligenta a consumului...
Eu am un Shelly 3Em
Merci.

**Comment by cnecrea** [comment]
Salut! 

Toate integrările vor avea această funcție, doar că trebuie să ne gândim la un lucru: atunci când a fost dezvoltată, opțiunea de trimitere a indexului nu era disponibilă. 

Cu timpul, se vor adăuga.

**Comment by edmund-1** [comment]
Am diferențe de 0.5% între ce afișează Shelly ca și consum și indexul citit de pe contor (contor neinteligent). 
Deci, sfatul meu este ca opțiunea de raportare automată să se poată face automat (posesorul își asumă riscul) sau în urma unui audit a indexului și o eventuală corecție înainte de raportare.
Eu am un Shelly EM (SHEM).

**Comment by cnecrea** [comment]
> Am diferențe de 0.5% între ce afișează Shelly ca și consum și indexul citit de pe contor (contor neinteligent). Deci, părerea mea este ca opțiunea de raportare automată să se poată face automat (posesorul își asumă riscul) sau în urma unui audit a indexului și o eventuală corecție înainte de raportare. Eu am un Shelly EM (SHEM).

slaut,

Da, bineînțeles. Dacă ai un cititor de contor, asta nu înseamnă că datele vor fi 100% fiabile. Ele trebuie “șlefuite” pentru a deveni complet precise, iar pentru asta există soluții.

---
### ☕ Susține dezvoltatorul

Dacă ți-a plăcut această integrare și vrei să sprijini munca depusă, **invită-mă la o cafea**! 🫶  
Nu costă nimic, iar contribuția ta ajută la dezvoltarea viitoare a proiectului. 🙌  

[![Buy Me A Coffee](https://img.shields.io/badge/Buy%20Me%20A%20Coffee-Susține%20dezvoltatorul-orange?style=for-the-badge&logo=buy-me-a-coffee)](https://buymeacoffee.com/cnecrea)

Mulțumesc pentru sprijin, apreciez fiecare gest de susținere! 🤗

**Comment by njoythegame** [comment]
Pentru transmitere index se face intai un POST la https://hidroelectrica-svc.smartcmobile.com/Service/SelfMeterReading/GetPreviousMeterRead cu urmatoarele:

`{"LanguageCode":"RO","Distributor":"","CustomerNumber":"","UserID":XXXXXX,"UtilityAccountNumber":"YYYYYYYYY","BasicValue":""}`

UserID si UtilityAccountNumber le avem deja.

Cu o parte din datele returnate facem dar si cu indexul nou se face un POST la https://hidroelectrica-svc.smartcmobile.com/Service/SelfMeterReading/SubmitSelfMeterRead

`{"UsageSelfMeterReadEntity":[{"contractAccountID":"1231231231","accountID":"234234234234","equipmentNo":"123132","registerNo":"001","registerType":"E3","uom":"KWH","preDecimals":"08","postDecimals":"09","noMROrder":"","prevMRResult":"999999","prevMRDate":"2025-01-01T00:00:00Z","prevMRRsn":"02","prevMRCat":"01","serialNumber":"456456456","pod":"555555555555","registerCat":"1.8.0","distributor":"Distributie XXXXX","meterInterval":"lunile 1\/4\/7\/10","supplier":"NNNNNNNN","distCustomer":"NUME","distCustomerId":"80000000","distContract":"1","distContractDate":"01\/01\/2000 00:00:00","newmeterread":"9999","NewMeterReadDate":"01\/01\/2025"}],"UserId":"7777777","UtilityAccountNumber":"80000000"}`

Indexul nou e "newmeterread".

Bineinteles, ca sa poti trimite trebuie sa fie in intervalul de trimitere index. Parca aici era: https://hidroelectrica-svc.smartcmobile.com/Service/SelfMeterReading/GetWindowDatesENC
Ai OpeningDate si ClosingDate ale fiecarei luni. 

Din pacate nu e prea stabil API-ul astora. Ori pica ori se "actualizeaza". Dar decat nimic e ok si asta.

**Comment by cnecrea** [comment]
Da, @njoythegame, am observat și eu acest lucru. Hidroelectrica și MyElectrica au aceeași problemă, par să fie făcute una pentru cealaltă. Dar asta avem, deocamdată. Poate, pe viitor, vor avea o stabilitate mai bună.

La acest endpoint, da, sunt valorile pentru citirea/trimiterea indexului.

API_GET_MULTI_METER_READ_DATE = f"{API_BASE_URL}/Service/SelfMeterReading/GetWindowDatesENC"


```yaml
{
    "version": "7.5.2",
    "status_code": 200,
    "responsestatus": 1,
    "request_time": "2025-01-24 11:52:43 PM",
    "response_time": "2025-01-24 11:52:43 PM",
    "result": {
        "Status": 1,
        "Message": "Success",
        "MessageCode": null,
        "Data": {
            "OpeningDate": "24",
            "ClosingDate": "28",
            "NextMonthOpeningDate": "24/02/2025",
            "NextMonthClosingDate": "28/01/2025",
            "Is_Window_Open": "Lvd14RzCdqvyc/gNj39CmBM="
        }
    }
}
```

O să mă uit zilele acestea să văd dacă reușesc să creez un senzor cu POST. Momentan, nu sunt prea inspirat și prefer să nu mă complic. 😊

---

### 💡 Contribuie la dezvoltare

Îți place această integrare? **Arată-ți aprecierea!** 🎉  
O simplă invitație la o cafea poate face diferența și susține viitoarele actualizări. ☕  

[![Buy Me A Coffee](https://img.shields.io/badge/Buy%20Me%20A%20Coffee-Contribuie%20la%20dezvoltare-orange?style=for-the-badge&logo=buy-me-a-coffee)](https://buymeacoffee.com/cnecrea)

Mulțumesc pentru sprijinul tău, ajută enorm! 🙌
