### ISSUE TITLE
Warning de autentificare

### ISSUE THREAD

**Issue by zahareevici** [cnecrea/hidroelectrica#19]
### Descrieți problema

Salutare, 
Desi integrarea lucreaza ok!
In log-uri vad acest WARNING:

### Versiunea integrării

2.5.0

### Loguri relevante

```yaml

This error originated from a custom integration.

Logger: custom_components.hidroelectrica.api
Source: custom_components/hidroelectrica/api.py:350
integration: Hidroelectrica România (documentation, issues)
First occurred: January 21, 2025 at 2:54:44 PM (27 occurrences)
Last logged: 4:56:06 PM

Am primit 401 la GetMultiMeter (Detalii contor), încerc re-autentificare...
# ↑↓ Introduceți logurile aici, nu ștergeți liniile indicate cu săgeți
```

### Ați încercat să dați restart?

Da

### Sistem de operare

Home Assistant OS
