### ISSUE TITLE
GetUsageGeneration (Istoric consum/generare): 500

### ISSUE THREAD

**Issue by rursache** [cnecrea/hidroelectrica#25]
### Ați citit secțiunea FAQ.md?

Da, am citit secțiunea FAQ.md și nu am găsit răspunsul la problema mea.

### Descrieți problema

Dupa setup cu user/pass valide (cont existent, client activ cu istoric de indecsi si facturi) primesc:
```
Failed setup, will retry: Update error: Eroare la cererea GetUsageGeneration (Istoric consum/generare): 500, {"version":"7.5.2","status_code":500,"responsestatus":-1,"request_time":"2025-05-17 07:46:02 PM","response_time":"2025-05-17 07:46:02 PM","error":{"StatusCode":500,"StatusMessage":"Internal Server Error","Message":"Contact to Adminstrator","status":-1}}
```

### Versiunea integrării

2.5.3

### Loguri relevante

```yaml
Logger: custom_components.hidroelectrica.coordinator
Source: custom_components/hidroelectrica/coordinator.py:171
integration: Hidroelectrica România (documentation, issues)
First occurred: 10:45:42 PM (7 occurrences)
Last logged: 10:48:14 PM

Eroare la actualizarea datelor Hidroelectrica: Eroare la cererea GetUsageGeneration (Istoric consum/generare): 500, {"version":"7.5.2","status_code":500,"responsestatus":-1,"request_time":"2025-05-17 07:46:02 PM","response_time":"2025-05-17 07:46:02 PM","error":{"StatusCode":500,"StatusMessage":"Internal Server Error","Message":"Contact to Adminstrator","status":-1}}
Eroare la actualizarea datelor Hidroelectrica: Eroare la cererea GetUsageGeneration (Istoric consum/generare): 500, {"version":"7.5.2","status_code":500,"responsestatus":-1,"request_time":"2025-05-17 07:46:24 PM","response_time":"2025-05-17 07:46:24 PM","error":{"StatusCode":500,"StatusMessage":"Internal Server Error","Message":"Contact to Adminstrator","status":-1}}
Eroare la actualizarea datelor Hidroelectrica: Eroare la cererea GetUsageGeneration (Istoric consum/generare): 500, {"version":"7.5.2","status_code":500,"responsestatus":-1,"request_time":"2025-05-17 07:47:07 PM","response_time":"2025-05-17 07:47:07 PM","error":{"StatusCode":500,"StatusMessage":"Internal Server Error","Message":"Contact to Adminstrator","status":-1}}
Eroare la actualizarea datelor Hidroelectrica: Eroare la cererea GetUsageGeneration (Istoric consum/generare): 500, {"version":"7.5.2","status_code":500,"responsestatus":-1,"request_time":"2025-05-17 07:48:07 PM","response_time":"2025-05-17 07:48:07 PM","error":{"StatusCode":500,"StatusMessage":"Internal Server Error","Message":"Contact to Adminstrator","status":-1}}
Eroare la actualizarea datelor Hidroelectrica: Eroare la cererea GetUsageGeneration (Istoric consum/generare): 500, {"version":"7.5.2","status_code":500,"responsestatus":-1,"request_time":"2025-05-17 07:48:14 PM","response_time":"2025-05-17 07:48:14 PM","error":{"StatusCode":500,"StatusMessage":"Internal Server Error","Message":"Contact to Adminstrator","status":-1}}
```

### Ați încercat să dați restart?

Da

### Sistem de operare

HASS (latest) in docker
